title = "Lewis Denham Parry"
description= "A website about Lewis Denham-Parry, if that's of interest to you"
languageCode = "en-gb"
theme = "hyde"

[params.social]
	twitter = "denhamparry"
	keybase = "denhamparry"
	github = "denhamparry"
	linkedin = "denhamparry"
  gravatar = "lewis@denhamparry.co.uk"
[params]
  description = "A website about Lewis Denham-Parry, if that's of interest to you"
[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"
