title = "Lewis Denham-Parry"
baseURL = "https://denhamparry.co.uk"
languageCode = "en-gb"
theme = "ananke"

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 9
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = ""
  description = "Random posts from Lewis Denham-Parry."
  facebook = "https://facebook.com/denhamparry"
  twitter = "https://twitter.com/denhamparry"
  instagram = "https://www.instagram.com/denhamparry/"
  youtube = "https://www.youtube.com/channel/UCBFyX1n9CbySYTsdsPei8aA"
  github = "https://github.com/denhamparry"
  gitlab = "https://gitlab.com/denhamparry"
  linkedin = "https://www.linkedin.com/in/denhamparry/"
  background_color_class = "bg-moon-grey"
  featured_image = "images/landing/landing00.png"
  recent_posts_number = 9