title = "Lewis Denham-Parry"
description= "A website about Lewis Denham-Parry, if that's of interest to you"
baseURL = "https://denhamparry.co.uk"
languageCode = "en-gb"
theme = "hugo-paper"

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 9
googleAnalytics = "UA-33113860-1"
disqusShortname = "denhamparry"
enableRobotsTXT = true


[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"
