[build]
  base = ""
  command = "hugo --gc -b $URL"
  publish = "/public"

[build.environment]
  HUGO_THEME = "hermit"

[context.deploy-preview]
  command = "hugo --gc -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
  command = "hugo --gc -b $DEPLOY_PRIME_URL"

[context.production.environment]
HUGO_VERSION = "0.52"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true