[build]
  base = "https://denhamparry.co.uk"
  command = "hugo --gc --themesDir ./themes -b $URL"
  publish = "/public"

[build.environment]
  HUGO_THEME = "hermit"

[context.deploy-preview]
  command = "hugo --gc --themesDir ./themes -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
  command = "hugo --gc --themesDir ./themes -b $DEPLOY_PRIME_URL"